"""Unit tests and property-based tests for OutputManager.

PBT invariants (PBT-03, PBT-07, PBT-08):
- test_property_sanitize_slug_length
- test_property_sanitize_slug_charset
- test_property_sanitize_slug_idempotent
- test_property_format_markdown_sections
- test_property_format_markdown_source_count
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from tests.conftest import (
    output_metadata_strategy,
    query_text,
    source_list,
    valid_slug_input,
)

from deep_research_agent.exceptions import OutputError
from deep_research_agent.output import OutputManager
from deep_research_agent.types import OutputMetadata, Source


_FIXED_TS = datetime(2026, 5, 25, 14, 30, 22, tzinfo=timezone.utc)
_REQUIRED_SECTIONS = [
    "## Metadata",
    "## Sources",
    "*Generated by Deep Research Agent*",
]


@pytest.fixture
def manager() -> OutputManager:
    return OutputManager()


# ---------------------------------------------------------------------------
# _sanitize_slug — example-based
# ---------------------------------------------------------------------------

class TestSanitizeSlug:
    def test_spaces_become_hyphens(self, manager: OutputManager) -> None:
        assert manager._sanitize_slug("quantum computing") == "quantum-computing"

    def test_special_chars_stripped(self, manager: OutputManager) -> None:
        assert manager._sanitize_slug("What is C++?") == "what-is-c"

    def test_truncated_to_50(self, manager: OutputManager) -> None:
        long = "a" * 100
        result = manager._sanitize_slug(long)
        assert len(result) <= 50

    def test_empty_returns_research(self, manager: OutputManager) -> None:
        assert manager._sanitize_slug("") == "research"

    def test_all_non_alpha_returns_research(self, manager: OutputManager) -> None:
        assert manager._sanitize_slug("???!!!") == "research"

    def test_no_leading_trailing_hyphens(self, manager: OutputManager) -> None:
        result = manager._sanitize_slug("  hello world  ")
        assert not result.startswith("-")
        assert not result.endswith("-")

    def test_consecutive_hyphens_collapsed(self, manager: OutputManager) -> None:
        result = manager._sanitize_slug("hello   world")
        assert "--" not in result


# ---------------------------------------------------------------------------
# _build_filename
# ---------------------------------------------------------------------------

class TestBuildFilename:
    def test_format(self, manager: OutputManager) -> None:
        name = manager._build_filename("quantum-computing", _FIXED_TS)
        assert name == "quantum-computing_20260525_143022.md"

    def test_ends_with_md(self, manager: OutputManager) -> None:
        assert manager._build_filename("test", _FIXED_TS).endswith(".md")


# ---------------------------------------------------------------------------
# _resolve_filename — collision handling
# ---------------------------------------------------------------------------

class TestResolveFilename:
    def test_no_collision_returns_base(self, manager: OutputManager, tmp_path: Path) -> None:
        path = manager._resolve_filename(tmp_path, "test", _FIXED_TS)
        assert path.name == "test_20260525_143022.md"

    def test_collision_appends_counter(self, manager: OutputManager, tmp_path: Path) -> None:
        base = tmp_path / "test_20260525_143022.md"
        base.write_text("existing")
        path = manager._resolve_filename(tmp_path, "test", _FIXED_TS)
        assert path.name == "test_20260525_143022_1.md"

    def test_multiple_collisions(self, manager: OutputManager, tmp_path: Path) -> None:
        (tmp_path / "test_20260525_143022.md").write_text("")
        (tmp_path / "test_20260525_143022_1.md").write_text("")
        path = manager._resolve_filename(tmp_path, "test", _FIXED_TS)
        assert path.name == "test_20260525_143022_2.md"


# ---------------------------------------------------------------------------
# _format_markdown
# ---------------------------------------------------------------------------

class TestFormatMarkdown:
    def _make_metadata(self) -> OutputMetadata:
        return OutputMetadata(
            query="What is quantum computing?",
            model_id="claude-test",
            session_id="sess-1",
            query_id="q-1",
            generated_at=_FIXED_TS,
            source_count=2,
        )

    def test_all_required_sections_present(self, manager: OutputManager) -> None:
        sources = [Source(url="https://a.com", title="A")]
        content = manager._format_markdown("Response text.", sources, self._make_metadata())
        for section in _REQUIRED_SECTIONS:
            assert section in content, f"Missing section: {section}"

    def test_contains_query(self, manager: OutputManager) -> None:
        content = manager._format_markdown("text", [], self._make_metadata())
        assert "quantum computing" in content

    def test_sources_listed(self, manager: OutputManager) -> None:
        sources = [Source(url="https://a.com", title="Source A")]
        content = manager._format_markdown("text", sources, self._make_metadata())
        assert "https://a.com" in content
        assert "Source A" in content

    def test_no_sources_shows_placeholder(self, manager: OutputManager) -> None:
        content = manager._format_markdown("text", [], self._make_metadata())
        assert "No sources recorded" in content

    def test_incomplete_marker_preserved(self, manager: OutputManager) -> None:
        text = "partial response\n\n---\n**[INCOMPLETE — stream interrupted]**"
        content = manager._format_markdown(text, [], self._make_metadata())
        assert "[INCOMPLETE" in content


# ---------------------------------------------------------------------------
# write() — end-to-end
# ---------------------------------------------------------------------------

class TestWrite:
    def _make_metadata(self, tmp_path: Path) -> OutputMetadata:
        return OutputMetadata(
            query="quantum computing",
            model_id="claude-test",
            session_id="sess-1",
            query_id="q-1",
            generated_at=_FIXED_TS,
            source_count=1,
        )

    def test_writes_file_and_returns_path(self, manager: OutputManager, tmp_output_dir: Path) -> None:
        metadata = self._make_metadata(tmp_output_dir)
        path = manager.write(
            response_text="Research content.",
            query="quantum computing",
            sources=[Source(url="https://a.com", title="A")],
            metadata=metadata,
            output_dir=tmp_output_dir,
        )
        assert path.exists()
        assert path.suffix == ".md"
        content = path.read_text(encoding="utf-8")
        assert "quantum computing" in content

    def test_creates_missing_output_dir(self, manager: OutputManager, tmp_path: Path) -> None:
        new_dir = tmp_path / "nested" / "output"
        metadata = OutputMetadata(
            query="test", model_id="m", session_id="s", query_id="q",
            generated_at=_FIXED_TS, source_count=0,
        )
        path = manager.write("text", "test", [], metadata, new_dir)
        assert path.exists()

    def test_raises_output_error_on_permission_failure(
        self, manager: OutputManager, tmp_output_dir: Path
    ) -> None:
        metadata = OutputMetadata(
            query="test", model_id="m", session_id="s", query_id="q",
            generated_at=_FIXED_TS, source_count=0,
        )
        with patch.object(manager, "_ensure_output_dir", side_effect=OutputError("no perms")):
            with pytest.raises(OutputError):
                manager.write("text", "test", [], metadata, tmp_output_dir)


# ---------------------------------------------------------------------------
# Property-Based Tests (PBT-03, PBT-07, PBT-08)
# ---------------------------------------------------------------------------

@pytest.mark.pbt
@given(query=valid_slug_input())
def test_property_sanitize_slug_length(query: str) -> None:
    """Invariant: slug length never exceeds 50 characters."""
    manager = OutputManager()
    result = manager._sanitize_slug(query)
    assert len(result) <= 50, f"Slug too long ({len(result)}): {result!r}"


@pytest.mark.pbt
@given(query=valid_slug_input())
def test_property_sanitize_slug_charset(query: str) -> None:
    """Invariant: slug contains only [a-z0-9-] and is non-empty."""
    manager = OutputManager()
    result = manager._sanitize_slug(query)
    assert result != "", "Slug must never be empty (fallback 'research' expected)"
    assert re.fullmatch(r"[a-z0-9][a-z0-9-]*[a-z0-9]|[a-z0-9]", result), (
        f"Slug contains invalid characters: {result!r}"
    )


@pytest.mark.pbt
@given(query=valid_slug_input())
def test_property_sanitize_slug_idempotent(query: str) -> None:
    """Idempotence: sanitize(sanitize(q)) == sanitize(q)."""
    manager = OutputManager()
    once = manager._sanitize_slug(query)
    twice = manager._sanitize_slug(once)
    assert once == twice, f"Not idempotent: {once!r} -> {twice!r}"


@pytest.mark.pbt
@given(
    response_text=st.text(min_size=0, max_size=500),
    sources=source_list(),
    metadata=output_metadata_strategy(),
)
def test_property_format_markdown_sections(
    response_text: str, sources: list[Source], metadata: OutputMetadata
) -> None:
    """Invariant: all required sections always present in Markdown output."""
    manager = OutputManager()
    content = manager._format_markdown(response_text, sources, metadata)
    for section in _REQUIRED_SECTIONS:
        assert section in content, f"Required section missing: {section!r}"


@pytest.mark.pbt
@given(
    response_text=st.text(min_size=0, max_size=200),
    sources=source_list(),
    metadata=output_metadata_strategy(),
)
def test_property_format_markdown_source_count(
    response_text: str, sources: list[Source], metadata: OutputMetadata
) -> None:
    """Invariant: source_count in metadata matches len(sources)."""
    # Rebuild metadata with correct source_count
    from dataclasses import replace
    metadata = replace(metadata, source_count=len(sources))
    manager = OutputManager()
    content = manager._format_markdown(response_text, sources, metadata)
    assert str(len(sources)) in content
