"""OutputManager — generates and writes Markdown research files.

Filename rules (RULE-OUT-02/03/04):
  - Slug: lowercase, spaces→hyphens, non-[a-z0-9-] stripped, max 50 chars
  - Filename: {slug}_{YYYYMMDD_HHMMSS}.md
  - Collision: append _1, _2, ... up to _999
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path

from deep_research_agent.exceptions import OutputError
from deep_research_agent.types import OutputMetadata, Source

logger = logging.getLogger(__name__)

_COLLISION_CAP = 999


class OutputManager:
    """Generates and writes Markdown research output files."""

    def write(
        self,
        response_text: str,
        query: str,
        sources: list[Source],
        metadata: OutputMetadata,
        output_dir: Path,
    ) -> Path:
        """Generate and write the Markdown research file. Returns the written path."""
        self._ensure_output_dir(output_dir)
        now = datetime.now(tz=timezone.utc)
        slug = self._sanitize_slug(query)
        output_path = self._resolve_filename(output_dir, slug, now)
        content = self._format_markdown(response_text, sources, metadata)
        try:
            output_path.write_text(content, encoding="utf-8")
        except OSError as exc:
            raise OutputError(
                f"Failed to write output file — check permissions for: {output_dir}"
            ) from exc
        logger.debug("Research output written: %s", output_path)
        return output_path

    def _sanitize_slug(self, query: str) -> str:
        """Convert a query string to a safe filename slug (RULE-OUT-02)."""
        slug = query.lower()
        slug = re.sub(r"\s+", "-", slug)
        slug = re.sub(r"[^a-z0-9-]", "", slug)
        slug = re.sub(r"-{2,}", "-", slug)
        slug = slug.strip("-")
        slug = slug[:50].rstrip("-")
        return slug or "research"

    def _build_filename(self, slug: str, timestamp: datetime) -> str:
        """Return '{slug}_{YYYYMMDD_HHMMSS}.md' (RULE-OUT-03)."""
        ts = timestamp.strftime("%Y%m%d_%H%M%S")
        return f"{slug}_{ts}.md"

    def _resolve_filename(self, output_dir: Path, slug: str, timestamp: datetime) -> Path:
        """Return a collision-free path, appending _N counter if needed (RULE-OUT-04)."""
        base_name = self._build_filename(slug, timestamp)
        candidate = output_dir / base_name
        if not candidate.exists():
            return candidate
        for counter in range(1, _COLLISION_CAP + 1):
            stem = base_name[:-3]  # strip .md
            candidate = output_dir / f"{stem}_{counter}.md"
            if not candidate.exists():
                return candidate
        raise OutputError(
            f"Could not find a unique filename after {_COLLISION_CAP} attempts for slug '{slug}'."
        )

    def _format_markdown(
        self,
        response_text: str,
        sources: list[Source],
        metadata: OutputMetadata,
    ) -> str:
        """Assemble the full Markdown document (RULE-OUT-01 — all 8 sections)."""
        title = metadata.query[:80] + ("..." if len(metadata.query) > 80 else "")
        generated_at = metadata.generated_at.strftime("%Y-%m-%dT%H:%M:%SZ")

        sources_section = self._format_sources(sources)
        usage = metadata.token_usage

        return (
            f"# Research: {title}\n\n"
            "---\n\n"
            "## Metadata\n\n"
            "| Field | Value |\n"
            "|---|---|\n"
            f"| Query | {metadata.query} |\n"
            f"| Model | {metadata.model_id} |\n"
            f"| Generated | {generated_at} |\n"
            f"| Session ID | {metadata.session_id} |\n"
            f"| Query ID | {metadata.query_id} |\n"
            f"| Input Tokens | {usage.input_tokens if usage else 0} |\n"
            f"| Output Tokens | {usage.output_tokens if usage else 0} |\n"
            f"| Total Tokens | {usage.total_tokens if usage else 0} |\n"
            f"| Sources Found | {metadata.source_count} |\n\n"
            "---\n\n"
            f"{response_text}\n\n"
            "---\n\n"
            "## Sources\n\n"
            f"{sources_section}\n"
            "---\n\n"
            "*Generated by Deep Research Agent*\n"
        )

    def _format_sources(self, sources: list[Source]) -> str:
        if not sources:
            return "*No sources recorded.*\n"
        lines = []
        for i, source in enumerate(sources, 1):
            lines.append(f"{i}. [{source.title}]({source.url})")
            if source.description:
                lines.append(f"   {source.description}")
        return "\n".join(lines) + "\n"

    def _ensure_output_dir(self, output_dir: Path) -> None:
        """Create the output directory if it does not exist (RULE-OUT-05)."""
        try:
            output_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise OutputError(
                f"Cannot create output directory — check permissions for: {output_dir}"
            ) from exc
